#!/usr/bin/env python

# Updated version of Gynvael's howto script
# https://gynvael.coldwind.pl/?id=771

from openai import OpenAI
import sys
import os

client = OpenAI(
        api_key=os.environ['OPENAI_API_KEY'],
)

arg = ' '.join(sys.argv[1:])

r = client.chat.completions.create(
  model="gpt-3.5-turbo",
  #model="gpt-4",
  messages=[
        {"role": "system", "content": "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible."},
        {"role": "user", "content": f"Answer with only the actual command without any intro or explanation. What is the arch linux command line command to {arg}"}
    ]
)

text = r.choices[0].message.content

if "bash" in text:
    embed_start = text.find('bash') + 5
    embed_end = text.find('`', embed_start)
    text = text[embed_start:embed_end]

if text.startswith('`') and text.endswith('`'):
  text = text[1:-1]

print(text)

